version: '3.5'

networks:
  auth-network:
    name: auth-network

services:
  database:
    image: mariadb:latest
    expose:
      - 3306
    environment:
      MARIADB_ROOT_PASSWORD: 2WA=CP@!trGv_AnN
      MARIADB_DATABASE: diagro
      MARIADB_USER: diagro
      MARIADB_PASSWORD: 2WA=CP@!trGv_AnN
    networks:
      - auth-network

  auth:
    build: ./development
    image: service-auth:dev
    expose:
      - 80
    networks:
      - auth-network
    restart: always
    depends_on:
      - "database"
    volumes:
      - /home/diagro/service_auth:/diagro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.service_auth.entrypoints=websecure"
      - "traefik.http.routers.service_auth.rule=Host(`auth.diagro.dev`)"
      - "traefik.http.routers.service_auth.tls=true"
      - "traefik.http.routers.service_auth.tls.certresolver=production"