version: '3.5'

networks:
  auth-network:
    name: auth-network
  database-network:
    name: database-network
    external: true

services:
  auth:
    build: ./development
    image: service-auth:dev
    expose:
      - 80
    networks:
      - database-network
      - auth-network
    restart: always
    volumes:
      - /home/diagro/service_auth:/diagro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.service_auth.entrypoints=websecure"
      - "traefik.http.routers.service_auth.rule=Host(`auth.diagro.dev`)"
      - "traefik.http.routers.service_auth.tls=true"
      - "traefik.http.routers.service_auth.tls.certresolver=production"